### PR TITLE
Release Teacher 1.21.0 (54)

### PR DESCRIPTION
**Pull request by kristofnemere**
Teacher release 1.21.0 (54)

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kdeakinstructure — DISMISSED** [review]
QA 👍

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Review by kristofnemere — COMMENTED** [review]
Light mode 👍 on Samsun Galaxy A53 5G & Samsung Galaxy Tab S6 Lite (api lvl 31 both)

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kdeakinstructure — DISMISSED** [review]
QA 👍

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by hermannakos — APPROVED** [review]

**Pull request merged**
