### PR TITLE
[Student] Fix SignedInUser not being cleared on logout

### PR DESCRIPTION
**Pull request by JordanMarshall**

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1005998&projectid=20)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|0
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by joehoag** [comment]
Could you run the LoginE2ETest against these changes?  It could be affected.

**Comment by StephenBrough** [comment]
@joehoag LoginE2E passed locally for me with this PR

**Comment by joehoag** [comment]
Thanks for testing, @StephenBrough.

**Pull request merged**
