### PR TITLE
[MBL-16365][Student] Migrate file download to worker

### PR DESCRIPTION
**Pull request by hermannakos**
Test plan: The functionality should be the same as before. Test downloading files:
- File List
- Inbox Attachments
- Module files

refs: MBL-16365
affects: Student
release note: none

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kristofnemere — APPROVED** [review]
QA+1

**Review by tamaskozmer — APPROVED** [review]

**Pull request merged**
