### PR TITLE
Release Teacher 1.27.0 (61)

### PR DESCRIPTION
**Pull request by hermannakos**

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kdeakinstructure — DISMISSED** [review]

**Comment by kdeakinstructure** [comment]
QA 👍

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Review by kristofnemere — APPROVED** [review]

**Pull request merged**
