### PR TITLE
Release Student 6.21.2 (246)

### PR DESCRIPTION
**Pull request by tamaskozmer**

### CODE REVIEW

**Review by hermannakos — APPROVED** [review]

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by tamaskozmer** [comment]
QA + 1

**Comment by kristofnemere** [comment]
QA + 1

**Review by hermannakos — APPROVED** [review]

**Review by kristofnemere — APPROVED** [review]

**Pull request merged**
