### PR TITLE
[MBL-16957][Student] Offline LGO support

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test plan: 
- Test all the screens where LGO has an effect.
- Verify that it works both in offline and online mode.
- Verify that scores are correctly displayed when LGO is turned off.

refs: MBL-16957
affects: Student
release note: none

## Checklist

- [x] Tested in dark mode
- [x] Tested in light mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kristofnemere — APPROVED** [review]

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Pull request merged**
