### PR TITLE
[MBL-16393][Teacher] Fixed announcement routing

### PR DESCRIPTION
**Pull request by hermannakos**
refs: MBL-16393
affects: Teacher
release note: none

test plan: See ticket.

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] A11y checked
- [ ] Approve from product or not needed

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kdeakinstructure — APPROVED** [review]
QA 👍  (automation test case which found this bug also passing)

**Review by tamaskozmer — APPROVED** [review]

**Review by kristofnemere — APPROVED** [review]

**Pull request merged**
