### PR TITLE
[MBL-17786][Student] UI glitches

### PR DESCRIPTION
**Pull request by andrasmaczak**
Test plan:

- Check file details screen on mobile landscape when file is locked
- Check file details screen on mobile landscape when file is not locked
- Check discussion list on dark mode

refs: MBL-17786
affects: student
release note: none

## Screenshots
Screenshot_20240919_092139
Screenshot_20240919_092119
Screenshot_20240920_094659
Screenshot_20240919_094131

## Checklist

- [x] Tested in dark mode
- [x] Tested in light mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by domonkosadam** [comment]
I'm not sure if it's in the scope of this ticket, but I think preview image's size could be fixed as well.

Screenshot_20240919_113605

**Comment by andrasmaczak** [comment]
Yeah, I agree, this should be fixed here as well. I will update it soon.

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Review by kristofnemere — APPROVED** [review]

**Comment by tamaskozmer** [comment]
I have seen a similar issue as Ádám. A think the preview should be constrained between the buttons and the top text and the size should depend on the available space.
file

**Review by kdeakinstructure — APPROVED** [review]

**Review by hermannakos — APPROVED** [review]

**Review by tamaskozmer — APPROVED** [review]

**Review by kristofnemere — APPROVED** [review]

**Review by domonkosadam — APPROVED** [review]

**Pull request merged**
