### PR TITLE
[MBL-18065][Student] Wi-Fi only toggle confirmation dialog fix

### PR DESCRIPTION
**Pull request by domonkosadam**
Test plan: See in ticket

refs: MBL-18065
affects: Student
release note: none

## Checklist

- [ ] Tested in dark mode
- [ ] Tested in light mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Native Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Review by tamaskozmer — APPROVED** [review]
QA + 1

**Pull request merged**
