### PR TITLE
Release Teacher 1.32.0 (69)

### PR DESCRIPTION
**Pull request by hermannakos**

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Review by tamaskozmer — APPROVED** [review]
QA + 1

**Pull request merged**
