### PR TITLE
[MBL-16875][Student] Navigate links offline

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test plan: Test that links embedded in HTML content (pages, assignment details, etc) route to the correct screens in offline mode as well.

refs: MBL-16875
affects: Student
release note: none

## Checklist

- [x] Tested in dark mode
- [x] Tested in light mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kristofnemere — APPROVED** [review]
QA+1

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Pull request merged**
