### PR TITLE
[MBL-17630][Student][Teacher] Calendar Redesign Focus Management Issues when selecting Calendar

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test plan: In the ticket

refs: MBL-17630
affects: Student, Teacher
release note: none

## Checklist

- [x] Tested in light mode
- [x] A11y checked

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Review by hermannakos — APPROVED** [review]

**Pull request merged**
