### PR TITLE
[MBL-15646][Student][Teacher] Update Firebase services and Google dependencies

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test plan: Smoke test the app and test main Firebase functions:
- Analytics can be tested in debug view: https://firebase.google.com/docs/analytics/debugview
- Push notifications can be tested out of the box.
- Remote config can be tested by adding logs to remote config fetching in code (low priority, I think this is not necessary to test again, I verified and the fetch works)

refs: MBL-15646
affects: Teacher, Student
release note: none

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Review by hermannakos — APPROVED** [review]

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Pull request merged**
