### PR TITLE
[MBL-17253][Student] App crashes when opened from Teacher Student View

### PR DESCRIPTION
**Pull request by kristofnemere**
Test plan: open student app from teacher by student view

refs: MBL-17253
affects: Student
release note: Fixed StudentView crash.

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by tamaskozmer — APPROVED** [review]

**Pull request merged**
