### PR TITLE
Release Student 6.21.0 (244)

### PR DESCRIPTION
**Pull request by kdeakinstructure**
Student release 6.21.0 (244)

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Review by kristofnemere — APPROVED** [review]

**Review by hermannakos — APPROVED** [review]

**Pull request merged**
