### PR TITLE
[MBL-16562][Student][Teacher] Removed kotlin-android-extensions from libraries.

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test plan: Smoke test both apps. Features that are more affected by these changes:
- Login screens
- Document scanner
- RCEditor
- Empty view
- Media player (seeing media submissions in full screen)
- Edit Dashboard
- Discussion redesign
- K5 screenes
- Theme selector
- Floating recording view
- Attachments in messages
- Share extension
- Avatar cropping

refs: MBL-16562
affects: Student, Teacher
release note: none

## Checklist

- [x] Follow-up e2e test ticket created or not needed
- [x] Run E2E test suite or not needed
- [x] Tested in dark mode
- [x] Tested in light mode
- [x] A11y checked
- [x] Approve from product or not needed

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Review by kristofnemere — APPROVED** [review]

**Pull request merged**
