### PR TITLE
[MBL-17004][Student] Multiple user support

### PR DESCRIPTION
**Pull request by kristofnemere**
Test plan: 
- test auto sync, it should run for the current user
- test removing previous user removes the db and files of it
- test change user offline
- test login landing page actions offline

refs: MBL-17004
affects: Student
release note: none

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by hermannakos — APPROVED** [review]
QA + 1

**Review by tamaskozmer — APPROVED** [review]

**Pull request merged**
