### PR TITLE
[MBL-17133][Student] Disable offline in K5

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test plan: Check if offline features are disabled for K5 users. Verify that the offline feature flag works correctly (on/off) for default users.

refs: MBL-17133
affects: Student
release note: none

## Checklist

- [x] Tested in light mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by hermannakos — APPROVED** [review]
QA + 1

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Pull request merged**
