### PR TITLE
[MBL-17945][Student][Parent] Filter hidden New Quizzes in the Grades list

### PR DESCRIPTION
**Pull request by domonkosadam**
Test plan: See ticket

refs: MBL-17945
affects: Student, Parent
release note: Hidden New Quizzes are now not displayed in the Grades list

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [ ] Run E2E test suite
- [ ] Tested in dark mode
- [ ] Tested in light mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Review by tamaskozmer — CHANGES_REQUESTED** [review]
QA + 1 for the Student/Parent app. However I think we need to make these changes in the new Parent app as well. I would do the filtering in the `ViewModel` in that case so if we integrate that later in the Student app it won't be forgotten and also we could avoid some duplication as well.

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Native Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Native Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by tamaskozmer — APPROVED** [review]

**Comment by tamaskozmer** [comment]
QA + 1

**Pull request merged**
