### PR TITLE
[MBL-16348][Student][Teacher] Login redesign 

### PR DESCRIPTION
**Pull request by hermannakos**
refs: MBL-16348
affects: Student, Teacher
release note: Redesigned the Login screen.

test plan: Check the new login screen. Previous logins/schools etc.

## Checklist

- [x] Follow-up e2e test ticket created or not needed
- [x] Tested in dark mode
- [x] Tested in light mode
- [x] A11y checked
- [x] Approve from product or not needed

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by tamaskozmer — APPROVED** [review]

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Review by kristofnemere — APPROVED** [review]

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kristofnemere — APPROVED** [review]

**Pull request merged**
