### PR TITLE
Update readme with student/teacher build status

### PR DESCRIPTION
**Pull request by JordanMarshall**
Also updates the parent build command

### CODE REVIEW

**Comment by joehoag** [comment]
I clicked on the build status links (on the main github page in your branch) and they sent me to a blank page.

**Comment by JordanMarshall** [comment]
It seems GitHub automatically makes markdown images clickable and I don't think that can be disabled. Clicking on the build status loads the build status image in a new page (at least for me). I could make it link to the respective bitrise projects, but I don't believe those are publicly accessible.

**Comment by joehoag** [comment]
Oh, ok, so it gives some kind of status while the build is taking place.  Now I get it.

**Comment by JordanMarshall** [comment]
These badges are for the open source projects that could fail to build if we change secrets without updating the open source data.

**Pull request merged**
