### PR TITLE
[MBL-17732][All] Making a conversation 'unread' by clicking on the toolbar 'unread' icon will not make the item disappear from 'archived' list

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test plan: In the ticket

refs: MBL-17732
affects: All
release note: none

## Checklist

- [x] Tested in light mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Review by hermannakos — APPROVED** [review]

**Review by kristofnemere — APPROVED** [review]
QA+1

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Pull request merged**
