### PR TITLE
[MBL-17668][Student][Teacher] -  Refactor E2E tests to handle new discussion redesign as default

### PR DESCRIPTION
**Pull request by kdeakinstructure**
Major refactor on E2E tests to handle new discussion redesign as default in both the Teacher and Student apps.
Rename, restructure some page objects.
Add some util functions.
Separate native and web view based Discussion Details Page.

refs: MBL-17668
affects: Teacher, Student
release note: none

## Checklist

- [x] Run E2E test suite

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by tamaskozmer — APPROVED** [review]

**Pull request merged**
