### PR TITLE
[MBL-18153][All] Removed custom submit feature idea action

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test plan: In the ticket

refs: MBL-18153
affects: All
release note: none

## Checklist

- [ ] Tested in light mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Native Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Native Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by domonkosadam** [comment]
What's the reason we completely downgraded this option? I checked in the iOS app and its behavior is the same to this new one. I think the old solution, like in the Parent app, is much more convenient for users.

**Pull request merged**
