### PR TITLE
[MBL-17278][Teacher] Bulk module update snackbars

### PR DESCRIPTION
**Pull request by hermannakos**
Test plan: See ticket for design. Test if the correct snackbar shows for every event. The 'Can't publish...' snackbars are blocked by api changes, we'll revisit them when the apis are ready.

refs: MBL-17278
affects: Teacher
release note: none

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kristofnemere — APPROVED** [review]
QA+1

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Pull request merged**
