### PR TITLE
[MBL-17608][Student][Teacher] Students without permissions can message entire sections by typing section name

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test plan: In the ticket. Smoke test the same functionality in the Teacher app. This change affects that as well since that part of the Inbox screen is shared.

refs: MBL-17608
affects: Student, Teacher
release note: none

## Checklist

- [x] Tested in light mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by hermannakos — APPROVED** [review]

**Review by kristofnemere — APPROVED** [review]
QA+1

**Pull request merged**
