### PR TITLE
[MBL-17058] Sync progress unit tests

### PR DESCRIPTION
**Pull request by hermannakos**
Test plan: Quick smoke test of the progress screen.

refs: MBL-17058
affects: Student
release note: none

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kristofnemere — APPROVED** [review]

**Review by tamaskozmer — APPROVED** [review]

**Comment by kdeakinstructure** [comment]
Sync fails when too many files are selected. (Check with my sandbox, reach out to me via Slack for the credentials).
However, after clicking on the 'Retry', it will be completed, but only some of the files will be downloaded eventually.

**Pull request merged**
