### PR TITLE
[MBL-16469][Student][Teacher] Inbox swipe gestures

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test plan:
- Test swipe actions in both apps

Some test notes:
- Archive action is not available in archived folder
- Archive action does not remove messages from starred folder (archived messages can be starred as well)

refs: MBL-16469
affects: Student, Teacher
release note: Added swipe actions to Inbox.

## Checklist

- [x] Follow-up e2e test ticket created or not needed
- [x] Run E2E test suite or not needed
- [x] Tested in dark mode
- [x] Tested in light mode
- [x] A11y checked
- [x] Approve from product or not needed

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kristofnemere — APPROVED** [review]
Nice work!

**Review by hermannakos — APPROVED** [review]

**Pull request merged**
