### PR TITLE
[MBL-15743][Teacher] Student Annotation support

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test plan: Verify grading and annotating student annotation submissions works. You can test this only on beta currently, I marked the PR draft, so we wouldn't merge before deploying the feature to production.

refs: MBL-15743
affects: Teacher
release note: Added support for student annotation submission type.

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by kdeakinstructure** [comment]
QA 👍

**Review by kdeakinstructure — APPROVED** [review]

**Review by hermannakos — APPROVED** [review]
LGTM!

**Pull request merged**
