### PR TITLE
[MBL-15512][Student][Teacher] Update ExoPlayer library

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test plan: Thoroughly smoke test every part of both the apps where we do video playback. Compare it to the current version from the play store.

Places in the app for video playback:
- Video or audio submission in the Speed Grader (teacher)
- Video or audio submission in the submission details screen (student)
- Opening a video in full screen view from the above two screens
- Opening a video or audio comment in the submission details/Speed Grader in Teacher (in the student we open these externally)
- Posting a video comment in submission details/Speed Grader and opening the preview after capturing the video.
- Opening a media file from the Files feature.

refs: MBL-15512
affects: Teacher, Student
release note: none

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Pull request merged**
