### PR TITLE
[MBL-18032][Student] Can't open embedded video file

### PR DESCRIPTION
**Pull request by kristofnemere**
Test plan: test all kind of links in webview of
- Assignment Details
- Syllabus
- Page Details

refs: MBL-18032
affects: Student
release note: Fixed an issue where embedded video urls would not open.

## Checklist

- [x] Tested in dark mode
- [x] Tested in light mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Native Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Review by tamaskozmer — APPROVED** [review]
QA + 1

**Pull request merged**
