### PR TITLE
[MBL-17174][Student][Teacher] Dependency update

### PR DESCRIPTION
**Pull request by hermannakos**
Test plan: Smoke test the apps.

refs: MBL-17174
affects: Student, Teacher
release note: none

## Checklist

- [x] Run E2E test suite
- [x] Tested in dark mode
- [x] Tested in light mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Comment by kdeakinstructure** [comment]
Student E2E successful run: https://app.bitrise.io/build/34e1870f-0b14-4e8b-80c0-a573cfdc5984

Teacher E2E successful run: https://app.bitrise.io/build/dddb9489-9a37-427c-8338-1f5387f152bf

**Review by kristofnemere — APPROVED** [review]
QA+1

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Pull request merged**
