### PR TITLE
Release Student 6.15.1 (233)

### PR DESCRIPTION
**Pull request by tamaskozmer**

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by balintbartok** [comment]
QA + 1

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Review by balintbartok — APPROVED** [review]
QA + 1

**Comment by SilBit-418** [comment]
@tamaskozmer

**Comment by SilBit-418** [comment]
@tamaskozmer

**Pull request merged**
