### PR TITLE
[MBL-17106][Student] Sync error Crashlytics reports

### PR DESCRIPTION
**Pull request by hermannakos**
refs: MBL-17106
affects: Student
release note: none

test plan: Check if the reports are made in Crashlytics.

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by tamaskozmer — APPROVED** [review]

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by tamaskozmer** [comment]
QA + 1

**Pull request merged**
