### PR TITLE
[MBL-17736][Student] Hide Studio submission type if video file submission is not allowed

### PR DESCRIPTION
**Pull request by hermannakos**
Test plan: See ticket.

refs: MBL-17736
affects: Student
release note: Fixed a bug, where Studio submission was allowed incorrectly.

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Pull request merged**
