### PR TITLE
[MBL-18036][Student] Calendar display crash for Discussions with checkpoints

### PR DESCRIPTION
**Pull request by kristofnemere**
Test plan: can be tested on beta, details in the ticket

refs: MBL-18036
affects: Student
release note: Added support for Discussion Checkpoints in Calendar.

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Native Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Native Parent Install Page</p>

**Review by tamaskozmer — APPROVED** [review]
QA + 1

**Pull request merged**
