### PR TITLE
[MBL-16786][Student] Offline module details

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test plan: Test module progression in offline mode.
Test notes: There are content that won't work in offline yet, because these detail pages haven't been done yet:
- Pages - will work after the Page Details ticket
- File Details - will work after the File Details ticket
- LTI content - will never work, we will add the not available offline screen in the next ticket
- Discussion - will never work because the redesign is a WebView, we will add the not available offline screen in the next ticket

refs: MBL-16786
affects: Student
release note: none

## Checklist

- [x] Tested in dark mode
- [x] Tested in light mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Review by kristofnemere — APPROVED** [review]
QA+1

**Comment by kdeakinstructure** [comment]
Please consider handling Quiz and Image type module items as well. They are also does not working (and I don't think they will, since quiz is a webview).

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Pull request merged**
