### PR TITLE
[MBL-17642][All] Upgrade AGP to 7.4.2

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test plan: Smoke test the app

refs: MBL-17642
affects: All
release note: none

## Checklist

- [x] Run E2E test suite
- [x] Tested in dark mode
- [x] Tested in light mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kristofnemere — APPROVED** [review]

**Review by hermannakos — APPROVED** [review]

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Pull request merged**
