### PR TITLE
[Student][MBL-13095] Hide group if enrollment is concluded and course is soft-concluded

### PR DESCRIPTION
**Pull request by JordanMarshall**
Ask me for repro creds

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1004969&projectid=20)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|0
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by joehoag** [comment]
Regarding android-vault: Why are we generating Ditto tapes for DashboardPageTest, when it contains only Interaction / MockCanvas tests?  Note also what we could probably just delete DashboardPageTest, since it has been superseded by DashboardInteractionTest.

**Comment by JordanMarshall** [comment]
@joehoag Good point. At the very least those dashboard tapes can be deleted (they are no longer generated, just got changed via search/replace for a specific endpoint that was updated), but I'll go ahead and remove DashboardPageTest as well.

**Pull request merged**
