### PR TITLE
[Flutter Parent][MBL-13835] Under construction screen

### PR DESCRIPTION
**Pull request by StephenBrough**
Waiting on some specs and image resources, but I think the few features we don't currently have are covered.

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1019307&projectid=20)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|0
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1019802&projectid=20)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|0
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by StephenBrough** [comment]
> I'm not entirely sure we needed tests for the undersconstruction view (I know some of them were breaking), but I suppose they will be solid placeholders for when we replace them with actual features.

Yeah, that was the idea. It'll break as soon as the feature gets implemented!

**Pull request merged**
