### PR TITLE
[MBL-17265][Student][Teacher] Calendar to teacher

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test plan: 
- Test the all the features of the calendar in the Teacher app. Compare the functionality with the web.
- Smoke test the Student calendar.

refs: MBL-17265
affects: Teacher
release note: Added calendar screen.

## Checklist

- [x] Run E2E test suite
- [x] Tested in dark mode
- [x] Tested in light mode
- [x] A11y checked

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Review by kristofnemere — APPROVED** [review]
QA+1

**Pull request merged**
