### PR TITLE
[MBL-16793][Student] Offline conference details

### PR DESCRIPTION
**Pull request by kristofnemere**
Test plan: test conference details online and offline

refs: MBL-16793
affects: Student
release note: none

## Checklist

- [x] Tested in dark mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by kdeakinstructure** [comment]
I think that Conference Details already worked in offline since you merged the Conference List pull request. Let's talk about this via Slack please.

**Review by hermannakos — APPROVED** [review]
QA + 1

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Pull request merged**
