### PR TITLE
Release Student 7.5.3 (266)

### PR DESCRIPTION
**Pull request by hermannakos**

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Comment by balintbartok** [comment]
QA + 1

**Review by balintbartok — APPROVED** [review]
QA + 1

**Review by domonkosadam — APPROVED** [review]
QA + 1

**Pull request merged**
