### PR TITLE
[MBL-16863][Student][Teacher][Parent] Fix code coverage

### PR DESCRIPTION
**Pull request by domonkosadam**
Test plan: Run 'full-test-coverage' workflow on Bitrise

refs: MBL-16863
affects: All
release note: none

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by hermannakos — APPROVED** [review]
Great job!

**Review by tamaskozmer — APPROVED** [review]

**Pull request merged**
