### PR TITLE
[MBL-17042][Teacher] Tablet: Posted grade page header color mismatch

### PR DESCRIPTION
**Pull request by domonkosadam**
Test plan: 
 - Open an assignment's submissions
 - Click 'Post Settings' in top right corner to open Post Policy Settings

refs: MBL-17042
affects: Teacher
release note: none

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [x] Tested in dark mode
- [x] Tested in light mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Review by tamaskozmer — APPROVED** [review]

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Pull request merged**
