### PR TITLE
[MBL-18086][All] Fix compose fonts

### PR DESCRIPTION
**Pull request by hermannakos**
Test plan: Smoke test the apps, we should use Lato everywhere.

refs: MBL-18086
affects: Student, Teacher, Parent
release note: none

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Native Parent Install Page</p>

**Review by domonkosadam — APPROVED** [review]
QA + 1

Just a question about our coding conventions.
We barely use the predefined Material design typography options, I think because it's easier to compare the manual values to the designs. Shall we replace the remaining few at simple Texts (not TextFields)?

**Comment by inst-danger** [comment]
<p>Native Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by tamaskozmer — APPROVED** [review]

**Pull request merged**
