### PR TITLE
[MBL-17776][Teacher] Assignments and discussions not opening from the Calendar on tablet

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test plan: Check that assignments and discussions route correctly on tablet.

refs: MBL-17776
affects: Techer
release note: Fixed an issue where assignments and discussions wouldn't open from the calendar on tablets.

## Checklist

- [x] Tested in light mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Review by hermannakos — APPROVED** [review]

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Pull request merged**
