### PR TITLE
[MBL-18058][Student] Navigation sections disabled are viewable via direct url

### PR DESCRIPTION
**Pull request by domonkosadam**
Test plan: Disabled Course tabs should not be available direct urls.

The main locations where url handling should be tested:

 - Opening external links when the app is not running
 - Embedded links to course web content: Page, Assignment, etc.
 - Embedded links to native components: Inbox

refs: MBL-18058
affects: Student
release note: Disabled tabs are now not available via links

## Checklist

- [ ] Tested in dark mode
- [x] Tested in light mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Native Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kristofnemere — CHANGES_REQUESTED** [review]
- [x] In the inbox if you click a disabled url it navigates to dashboard

**Comment by inst-danger** [comment]
<p>Native Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Native Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Native Parent Install Page</p>

**Review by kristofnemere — CHANGES_REQUESTED** [review]
- [ ] When disabled tab is opened with deeplink for the first time, it navigates
- [ ] When disabled tab is opened with deeplink, the InterWebsToApplication activity is not finished

Gonna send recordings in DM

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Native Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kristofnemere — APPROVED** [review]
QA+1

**Review by tamaskozmer — APPROVED** [review]

**Pull request merged**
