### PR TITLE
[MBL-17273][Student] Schedule reminder notification

### PR DESCRIPTION
**Pull request by kristofnemere**
Test plan:
- Can not set past reminder, should show an error
- For each assignment there just can be one notification at a time, it should update it theres a new
- Past reminders should be removed when the notification shows up
- Reminders should work after restarting the phone
- On logout reminders should be cancelled and rescheduled after login
- On Android 14 it should show a snackbar if reminders are not enabled in system settings

refs: MBL-17273
affects: Student
release note: none

## Checklist

- [ ] Tested in dark mode
- [ ] Tested in light mode
- [ ] A11y checked

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kdeakinstructure — APPROVED** [review]
QA 👍  (ticket for the related findings for the future)

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kdeakinstructure — APPROVED** [review]
QA 👍  (Checked the changes)

**Review by tamaskozmer — APPROVED** [review]
QA + 1

**Pull request merged**
