### PR TITLE
Release Parent 3.3.5 (40)

### PR DESCRIPTION
**Pull request by tamaskozmer**

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by hermannakos** [comment]
QA + 1

**Review by hermannakos — APPROVED** [review]

**Comment by tamaskozmer** [comment]
QA + 1

**Comment by kdeakinstructure** [comment]
QA 👍

**Review by kdeakinstructure — APPROVED** [review]

**Pull request merged**
