### PR TITLE
[MBL-17243][Student][Teacher] Migrate ExoPlayer to Media3

### PR DESCRIPTION
**Pull request by hermannakos**
Test plan: Test every player view in the apps. Submissions, files, etc.

refs: MBL-17243
affects: Student, Teacher
release note: none

## Checklist

- [x] Run E2E test suite

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Review by tamaskozmer — APPROVED** [review]

**Review by kristofnemere — APPROVED** [review]
QA+1

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Pull request merged**
