### PR TITLE
[MBL-17460][Student][Teacher] Edit nickname on course cards shows unexpected error if doing it twice

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test plan: See ticket. I fixed the same problem in the Student app as well. Also did some refactoring and moved the dialog to the common module to remove duplication.

refs: MBL-17460
affects: Student, Teacher
release note: none

## Checklist

- [x] Tested in light mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Review by hermannakos — APPROVED** [review]

**Pull request merged**
