### PR TITLE
[MBL-17256][All] - Change the Privacy Policy URL

### PR DESCRIPTION
**Pull request by kdeakinstructure**
Change the Privacy Policy URL from "https://www.instructure.com/canvas/privacy" to "https://www.instructure.com/privacy-security", since it seems like it has changed on the web and the old one only has alias on it.

Test plan: Check if the changed URL works in all the apps.

refs: MBL-17256
affects: Student, Teacher, Parent
release note: Change Privacy Policy URL in all apps.

- [x] Tested in dark mode
- [x] Tested in light mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by tamaskozmer — APPROVED** [review]
QA + 1

**Review by kristofnemere — APPROVED** [review]

**Pull request merged**
