### PR TITLE
[MBL-15975][All] LaTex equations rendering

### PR DESCRIPTION
**Pull request by hermannakos**
refs: MBL-15975
affects: All
release note: Rendering LaTex equations.

test plan: See ticket.

### CODE REVIEW

**Comment by hermannakos** [comment]
<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Review by tamaskozmer — APPROVED** [review]

**Pull request merged**
