### PR TITLE
[MBL-16173][Teacher] Grading and grading state gets confused after grading via To Do section

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test plan:
- Repro steps in the ticket, but one thing is not mentioned there. To reproduce the issue first you need to open that assignment details screen from the assignments list to have it cached. Than follow the steps in the ticket.
- I also fixed the issue that the todo item is not disappearing when all the assignments were graded for that item.

refs: MBL-16173
affects: Teacher
release note: none

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by kdeakinstructure** [comment]
> Test plan:
> 
> * Repro steps in the ticket, but one thing is not mentioned there. To reproduce the issue first you need to open that assignment details screen from the assignments list to have it cached. Than follow the steps in the ticket.
> * I also fixed the issue that the todo item is not disappearing when all the assignments were graded for that item.
> 
> refs: MBL-16173 affects: Teacher release note: none

As far as I remember, it is mentioned in the ticket as well that you need to open the assignment's details screen. It is mentioned within the first sentence.

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Review by kristofnemere — APPROVED** [review]

**Pull request merged**
