### PR TITLE
[MBL-16631][Student] Offline Dashboard

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test plan: Requirements are in the ticket. Test the Dashboard in both offline and online mode. Don't worry about the migration errors, I changed the DB to version 1, we will keep it that way until we merge back the feature branch to master.

refs: MBL-16631
affects: Student
release note: none

## Checklist

- [x] Follow-up e2e test ticket created or not needed
- [x] Run E2E test suite or not needed
- [x] Tested in dark mode
- [x] Tested in light mode
- [x] A11y checked
- [x] Approve from product or not needed

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kristofnemere — APPROVED** [review]
QA+1

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Review by hermannakos — APPROVED** [review]

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Pull request merged**
