### PR TITLE
[MBL-16470][Teacher] Integrate Inbox redesign

### PR DESCRIPTION
**Pull request by tamaskozmer**
The changes mostly affect the Teacher app, but there were also some fixes and improvements for the core Inbox code as well:
- Animate avatars back when selection mode is exited.
- Collapsing filter header.

Test plan:
- Verify that all the previously working behavior works as intended (Showing Inbox list, paging, filtering by course/group, filtering by scope, opening messages, pull to refresh, writing messages, updating the list after writing a message or changing/deleting an opened message).
- Verify that the new bulk actions are working correctly.
- Verify that all the data shown is correct (check with the previous version).
- Verify that the routing works correctly.
- Smoke test Inbox in Student app.

refs: MBL-16470
affects: Teacher
release note: Added bulk actions to Inbox

## Checklist

- [x] Follow-up e2e test ticket created or not needed
- [x] Run E2E test suite or not needed
- [x] Tested in dark mode
- [x] Tested in light mode
- [x] A11y checked
- [x] Approve from product or not needed

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kristofnemere — CHANGES_REQUESTED** [review]

**Review by kristofnemere — APPROVED** [review]

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Pull request merged**
