### PR TITLE
[MBL-16518][Student] - Refactor and extract API calls from Student E2E tests

### PR DESCRIPTION
**Pull request by kdeakinstructure**
Refactor and extract API calls from the case methods into private method calls.
Minor refactor + add some missing logs.

refs: MBL-16518
affects: Student
release note: none

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by tamaskozmer — APPROVED** [review]

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Pull request merged**
