### PR TITLE
[MBL-16787][Student] Not Available Offline screen

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test plan: Verify that the not available screen shows in the module progression when the content is not available offline. When the user is connected to the network nothing should change.
Test notes:
- Module item types that are never available offline: Discussion, Mastery Path selection, External tool
- Module items where the screen shown depends on what is selected in the "Manage Offline Content" screen: Page, Assignment, Quiz

refs: MBL-16787
affects: Student
release note: none

## Checklist

- [x] Tested in dark mode
- [x] Tested in light mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Pull request merged**
