### PR TITLE
[MBL-18080][Parent] Course details - Refactor refresh logic

### PR DESCRIPTION
**Pull request by kristofnemere**
Test plan: in the ticket

refs: MBL-18080
affects: Parent
release note: none

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Native Parent Install Page</p>

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Review by domonkosadam — APPROVED** [review]
QA + 1

**Review by tamaskozmer — APPROVED** [review]

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Native Parent Install Page</p>

**Pull request merged**
