### PR TITLE
[MBL-16702][Student] Offline sync worker integration

### PR DESCRIPTION
**Pull request by hermannakos**
Test plan: With app inspector check the worker's state.

refs: MBL-16702
affects: Student
release note: none

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by tamaskozmer — APPROVED** [review]

**Review by kristofnemere — APPROVED** [review]

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Pull request merged**
