### PR TITLE
[MBL-16904][Student][Teacher] Save environment feature flags

### PR DESCRIPTION
**Pull request by hermannakos**
Test plan: Check if the feature flags are saved to the AppDatabase.

refs: MBL-16904
affects: Student, Teacher
release note: none

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kristofnemere — APPROVED** [review]

**Review by tamaskozmer — APPROVED** [review]

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Pull request merged**
