### PR TITLE
[MBL-17492][Teacher] Opening left-side menu when on calendar page in landscape mode dismisses user account information

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test plan: In the ticket. I also added some clarification there about how to reproduce the issue.

refs: MBL-17492
affects: Teacher
release note: none

## Checklist

- [x] Tested in dark mode
- [x] Tested in light mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by hermannakos — APPROVED** [review]
QA + 1

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Pull request merged**
