### PR TITLE
[All] Don't require camera hardware

### PR DESCRIPTION
**Pull request by JordanMarshall**

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by joehoag** [comment]
So what does tools:replace="required" do?  (Couldn't find out from a few seconds of googling.)

**Comment by JordanMarshall** [comment]
https://developer.android.com/studio/build/manifest-merge#attribute_markers

**Comment by joehoag** [comment]
So were we competing with another manifest?

**Comment by JordanMarshall** [comment]
Yes, most likely CameraKit's manifest

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1006237&projectid=20)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|0
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Pull request merged**
