### PR TITLE
[MBL-15625][Student] Schedule a11y improvements

### PR DESCRIPTION
**Pull request by hermannakos**
refs: MBL-15625
affects: Student
release note: Accessibility improvements.

test plan: Using TalkBack mark schedule items as done and not done. TalkBack should announce witch item has been changed.

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by tamaskozmer — APPROVED** [review]

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Pull request merged**
