### PR TITLE
Cherrypick Calendar E2E tests fix

### PR DESCRIPTION
**Pull request by kdeakinstructure**
Cherrypick Calendar E2E tests fix.

### CODE REVIEW

**Review by tamaskozmer — APPROVED** [review]

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Pull request closed without merging**
