### PR TITLE
[MBL-17887][Student] - Add assertions to Grades E2E tests

### PR DESCRIPTION
**Pull request by kdeakinstructure**
Extend Grades and OfflineGrades E2E tests with assertions (due date, status, checkbox default states)
Refactor getDateInCanvasCalendarFormat method to handle custom parameter (prior it worked only with current date).
Add some page object methods.

refs: MBL-17887
affects: Student
release note: none

## Checklist

- [x] Run E2E test suite

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Review by kristofnemere — APPROVED** [review]

**Pull request merged**
