### PR TITLE
[MBL-17192][Student] Calendar kick-off

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test plan: Test the calendar view on the new Calendar screen. This is still in progress, see the ticket to know what's in scope of this PR.

refs: MBL-17192
affects: Student
release note: Calendar redesign

## Checklist

- [x] Tested in dark mode
- [x] Tested in light mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Pull request merged**
