### PR TITLE
[MBL16492][Teacher] - Create interaction test case for global announcements in Dashboard

### PR DESCRIPTION
**Pull request by kdeakinstructure**
Create interaction test case for global announcements in Dashboard.

refs: MBL-16492
affects: Teacher
release note: none

### CODE REVIEW

**Review by tamaskozmer — APPROVED** [review]

**Review by kristofnemere — APPROVED** [review]

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Pull request merged**
