### PR TITLE
[MBL-16044][Student][Teacher] - TestMedata annotation refactor + rename priorities

### PR DESCRIPTION
**Pull request by kdeakinstructure**
Remove 'manualOnly' unused parameter from TestMetaData annotation.
Rename priorities.

**### _REVIEW TIP: Significant changes only in TestMetadata.kt, CustomFileBuilder.kt and FileGenerator.kt classes.
Others are just applying the new priority names._**

refs: MBL-16044
affects: Student, Teacher
release note: none

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by tamaskozmer — APPROVED** [review]

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Pull request merged**
