### PR TITLE
[MBL-16472][Student][Teacher] New color palette

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test plan: 
- Review that the new colors are correct. You can check with the new palette, it's in the ticket.
- Test the app in dark/light mode and look for any issues where text is not correctly visible.
- Elements where we have a colored background (not white or black) text should be white in light mode and dark in dark mode. This only affects our hardcoded colors, brand/course colors will be tackled in the next PR. You can find these colors in the ticket.

refs: MBL-16472
affects: Student, Teacher
release note: New accessible color palette

## Checklist

- [x] Tested in dark mode
- [x] Tested in light mode
- [x] A11y checked
- [x] Approve from product

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by hermannakos — APPROVED** [review]
QA + 1

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Pull request merged**
