### PR TITLE
Fix breaking DashboardE2E test in offline branch

### PR DESCRIPTION
**Pull request by kdeakinstructure**
Fix breaking DashboardE2E test in offline branch. (should wait for the view and refactor scrolling process)

### CODE REVIEW

**Review by hermannakos — APPROVED** [review]

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Pull request merged**
