### PR TITLE
[MBL-15934][Student] Future courses show up on Dashboard

### PR DESCRIPTION
**Pull request by hermannakos**
refs: MBL-15934
affects: Student
release note: Fixed a bug where future courses would not show up on the Dashboard.

test plan: See ticket.

### CODE REVIEW

**Comment by hermannakos** [comment]
<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

**Comment by hermannakos** [comment]
<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Review by tamaskozmer — APPROVED** [review]

**Pull request merged**
