### PR TITLE
[MBL-16794][Student] Disable every functionality that is not available offline

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test plan: In the ticket

refs: MBL-16794
affects: Student
release note: none

## Checklist

- [x] Tested in light mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by hermannakos — APPROVED** [review]
QA + 1

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Pull request merged**
