### PR TITLE
[MBL-16195][Student][Teacher] window.location.pathname returns incomplete data

### PR DESCRIPTION
**Pull request by kristofnemere**
refs: MBL-16195
affects: Student, Teacher
release note: none

Test plan:
Test plan is in the ticket.

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by tamaskozmer — APPROVED** [review]

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Pull request merged**
