### PR TITLE
[MBL-17876][Student][Teacher] New course colors

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test plan:
- Check that the new course colors are present in the course color picker and are correct in both dark and light mode.
- Check if a course color is set it's dark mode counterpart will be used in dark mode and in the course color selector it will be selected.
- Smoke test the app in dark/light mode. The text should be dark in dark mode and light in light mode on the course color background.
- The same applies to the Canvas theme's button color.

refs: MBL-17876
affects: Student, Teacher
release note: New colors for course customization.

## Checklist

- [x] Tested in dark mode
- [x] Tested in light mode
- [x] Approve from product

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Review by hermannakos — APPROVED** [review]

**Pull request merged**
