### PR TITLE
[MBL-17251][Student] - Implement Drag and Drop functionality on CourseBrowser Page.

### PR DESCRIPTION
**Pull request by kdeakinstructure**
Implement Drag and Drop functionality on CourseBrowser Page.
Handles different users. (So all users has their own order)
Handles different courses. (So all courses has their own order)

refs: MBL-17251
affects: Student
release note: Drag and Drop functionality on Course Browser Page.

- [ ] Tested in dark mode
- [ ] Tested in light mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by kdeakinstructure** [comment]
Based on Android meeting conversation, this feature won't be merged.

**Pull request closed without merging**
