### PR TITLE
[MBL-17241][Student] One Ungraded quiz is included in the To Do list when there are multiple

### PR DESCRIPTION
**Pull request by kristofnemere**
Test plan: in the ticket.

refs: MBL-17241
affects: Student
release note: none

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by tamaskozmer — APPROVED** [review]
QA+1

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Pull request merged**
