### PR TITLE
[MBL-17322][Student][Teacher] Calendar animations

### PR DESCRIPTION
**Pull request by tamaskozmer**
Review notes:
- To understand each animation logic more easily I would suggest reviewing commit by commit.

Test plan:
- Test all the animations that are listed in the ticket.
- Test the whole calendar screen (without the filters and create actions). Everything should work correctly and should have the same behavior as in the Flutter version apart from the drag gesture animation which will be implemented in a separate ticket.

refs: MBL-17322
affects: Student, Teacher
release note: none

## Checklist

- [x] Tested in dark mode
- [x] Tested in light mode
- [x] A11y checked

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by hermannakos — APPROVED** [review]
QA + 1

**Pull request merged**
