### PR TITLE
[MBL-17107][Student] Fix act as user QR login

### PR DESCRIPTION
**Pull request by hermannakos**
refs: MBL-17107
affects: Student
release note: none

test plan: See ticket.

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Review by kristofnemere — APPROVED** [review]

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Pull request merged**
