### PR TITLE
[MBL-16880][Student] Offline submission details

### PR DESCRIPTION
**Pull request by kristofnemere**
Test plan: 
- the text entry type should work offline as well
- other types should show the not available offline screen or if it has a button it should show the offline warning dialog when clicked
- on the files tab the files in the list should have icon by type

refs: MBL-16880
affects: Student
release note: none

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by tamaskozmer — APPROVED** [review]

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Pull request merged**
