### PR TITLE
[MBL-16381][Student] Submission details enhancement

### PR DESCRIPTION
**Pull request by kristofnemere**
Test plan: in the ticket, can only be tested in beta environment yet

refs: MBL-16381
affects: Student
release note: Submission details comments are submission sensitive now.

## Checklist

- [ ] Follow-up e2e test ticket created or not needed
- [ ] Run E2E test suite or not needed
- [x] Tested in dark mode
- [x] Tested in light mode
- [ ] A11y checked
- [ ] Approve from product or not needed

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Review by tamaskozmer — APPROVED** [review]

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by tamaskozmer — APPROVED** [review]

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Pull request merged**
