### PR TITLE
[MBL-17242][All] Update Mockk dependency

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test plan: -

refs: MBL-17242
affects: All
release note: none

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by hermannakos — APPROVED** [review]

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Review by domonkosadam — APPROVED** [review]

**Pull request merged**
