### PR TITLE
[MBL-17428][Student][Teacher] Swipe down refreshes new discussion details page

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test plan: In the ticket.

refs: MBL-17428
affects: Student. Teacher
release note: Fixed a bug where swipe down refreshes redesigned discussions.

## Checklist

- [x] Tested in dark mode
- [x] Tested in light mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by hermannakos — APPROVED** [review]
QA + 1

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Pull request merged**
