### PR TITLE
[MBL-17109][Student] Fix offline Course grade

### PR DESCRIPTION
**Pull request by hermannakos**
refs: MBL-17109
affects: Student
release note: none

test plan: See ticket.

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by tamaskozmer — APPROVED** [review]
QA + 1

**Review by kristofnemere — APPROVED** [review]

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Pull request merged**
