### PR TITLE
Native parent todos & bug fixes

### PR DESCRIPTION
**Pull request by kristofnemere**
Implemented opening Discussion and Quiz assignments is calendar
Implemented different domain case when opening the app from a link
Fixed student selector blinking
Fixed invalid error state on courses screen when changing user
Fixed a flaky test in DashboardInteractionTest
Fixed the icon of quiz type assignments on the grades tab

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Native Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by tamaskozmer — APPROVED** [review]
QA + 1

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Native Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Pull request merged**
