### PR TITLE
[MBL-17231][All] Update target SDK to 34

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test plan: Smoke test all the apps. Most critical parts are background services (offline sync, file upload, download, submissions), notifications, platform interactions (camera, file picker, permissions), widgets.

refs: MBL-17231
affects: All
release note: none

## Checklist

- [x] Run E2E test suite
- [x] Tested in dark mode
- [x] Tested in light mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by hermannakos — APPROVED** [review]
QA + 1

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Pull request merged**
