### PR TITLE
[MBL-16587][Student] Acceptable Use Policy displayed on K5 webviews after accepting it after mobile login

### PR DESCRIPTION
**Pull request by kristofnemere**
Test plan: Need to check if all webview where we load url (quiz, discussions etc.) works fine after accepting the use policy (in that particular login, when accepting it) in student and teacher also.

refs: MBL-16587
affects: Student, Teacher
release note: none

## Checklist

- [x] Follow-up e2e test ticket created or not needed
- [x] Run E2E test suite or not needed
- [x] Tested in dark mode
- [x] Tested in light mode
- [x] A11y checked
- [x] Approve from product or not needed

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by tamaskozmer — APPROVED** [review]
QA + 1

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Pull request merged**
