### PR TITLE
[MBL-16355][Student] Fix File Upload crash

### PR DESCRIPTION
**Pull request by hermannakos**
refs: MBL-16355
affects: Student
release note: Fixed a crash when uploading files.

test plan:

### CODE REVIEW

**Review by tamaskozmer — APPROVED** [review]

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kristofnemere — APPROVED** [review]

**Pull request merged**
