### PR TITLE
[MBL-17593][Student][Teacher] Localize calendar week first day

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test plan: Check if the first day of the calendar is set according to the correct locale. You need to set the locale in the user settings in Canvas, can be done on the web.

refs: MBL-17593
affects: Student, Teacher
release note: none

## Checklist

- [x] Tested in dark mode
- [x] Tested in light mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kristofnemere — APPROVED** [review]
QA+1

**Review by hermannakos — APPROVED** [review]

**Pull request merged**
