### PR TITLE
Resolve conflicts

### PR DESCRIPTION
**Pull request by hermannakos**

### CODE REVIEW

**Review by kristofnemere — APPROVED** [review]

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Pull request merged**
