### PR TITLE
[MBL-16320][Student] Search (magnifying glass) icon on Pages List page disappearing under specific circumstance

### PR DESCRIPTION
**Pull request by tamaskozmer**
refs: MBL-16320
affects: Student
release note: none

test plan: In the ticket

## Checklist

- [x] Follow-up e2e test ticket created or not needed
- [x] A11y checked
- [x] Approve from product or not needed

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kristofnemere — APPROVED** [review]

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Review by hermannakos — APPROVED** [review]

**Comment by stephaniegilbert944** [comment]
Thank you

**Pull request merged**
