### PR TITLE
[MBL-17325][Student] Unsupported push notifications can be toggled

### PR DESCRIPTION
**Pull request by kristofnemere**
Test plan: in the ticket

refs: MBL-17325
affects: Student
release note: Updated push notification categories.

## Checklist

- [x] Follow-up e2e test ticket created or not needed
- [x] Run E2E test suite

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by tamaskozmer — APPROVED** [review]

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Pull request merged**
