### PR TITLE
[MBL-17948][All] Common settings code + new theme selector

### PR DESCRIPTION
**Pull request by hermannakos**
Test plan: Check the settings page in all apps.

refs: MBL-17948
affects: Student, Teacher, Parent
release note: none

## Checklist

- [x] Follow-up e2e test ticket created or not needed
- [x] Run E2E test suite
- [x] Tested in dark mode
- [x] Tested in light mode
- [ ] A11y checked
- [ ] Approve from product

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by tamaskozmer — CHANGES_REQUESTED** [review]
QA findings:
- [x] When we are scrolled down the animation looks weird, because the other theme that's revealing is completely scrolled up.
- [ ] There is a very short blinking at the start of the animation
- [x] The brand colored border is not set correctly when changing theme. I think we should set it's color after the theme is changed, and we might need to introduce some delay here as well, because it's not happening instantly. Until the delay I wouldn't show the border at all. Or a more simpler solution would be to use the borderDarkest color.

**Comment by kdeakinstructure** [comment]
> QA findings:
> 
> * [ ]  When we are scrolled down the animation looks weird, because the other theme that's revealing is completely scrolled up.
> * [ ]  There is a very short blinking at the start of the animation
> * [ ]  The brand colored border is not set correctly when changing theme. I think we should set it's color after the theme is changed, and we might need to introduce some delay here as well, because it's not happening instantly. Until the delay I wouldn't show the border at all. Or a more simpler solution would be to use the borderDarkest color.

I would add to Tamas' QA review that on tablet the animation won't apply on the split screen's right side (so it became instantly dark/light while the narrower left side applies the animation).
Also, a minor thing is that the toolbar left-right side height might not be the same.

See attached video.

https://github.com/user-attachments/assets/2a889639-eecf-41b7-8a10-b00b41a74ae6

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Native Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Native Parent Install Page</p>

**Comment by tamaskozmer** [comment]
> > QA findings:
> > 
> > * [ ]   When we are scrolled down the animation looks weird, because the other theme that's revealing is completely scrolled up.
> > * [ ]   There is a very short blinking at the start of the animation
> > * [ ]   The brand colored border is not set correctly when changing theme. I think we should set it's color after the theme is changed, and we might need to introduce some delay here as well, because it's not happening instantly. Until the delay I wouldn't show the border at all. Or a more simpler solution would be to use the borderDarkest color.
> 
> I would add to Tamas' QA review that on tablet the animation won't apply on the split screen's right side (so it became instantly dark/light while the narrower left side applies the animation). (However I'd cut off the split view from the settings page at all because we does show anything on the right side neither of the menu points.) Also, a minor thing is that the toolbar left-right side height might not be the same.
> 
> See attached video.
> 
>  app-theme-animation-does-not-apply-on-split-screen-right-side.mp4

I think we can create a separate ticket for changing the layout and removing the split view, but I wouldn't do anything about this in this PR.

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Native Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Native Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Native Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Native Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Native Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Native Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Native Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Pull request merged**
