### PR TITLE
[MBL-16277][Student][Teacher] Dark mode brand color modifications

### PR DESCRIPTION
**Pull request by tamaskozmer**
refs: MBL-16277
affects: Student, Teacher
release note: Fixed dark mode accessibility issues regarding brand and course colors.

test plan:
- Test the brand colors, brand button colors and custom course colors in dark mode.
- For this you need to set brand colors in your sandbox that are not accessible in dark mode.
- Further requirements and info about how we manipulate the custom colors can be found in the document attached to the ticket.
- Test also light/dark theme change and verify that the colors change.
- We changed code everywhere through the app so a smoke test in dark/light theme is needed as well.

## Checklist

- [x] Follow-up e2e test ticket created or not needed
- [x] A11y checked
- [x] Approve from product or not needed

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Review by kristofnemere — APPROVED** [review]
Nice work!

**Review by hermannakos — APPROVED** [review]

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Pull request merged**
