### PR TITLE
[MBL-17154][Student] Add loading animation for offline content screen

### PR DESCRIPTION
**Pull request by kristofnemere**
Test plan: in the ticket

refs: MBL-17154
affects: Student
release note: none

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by tamaskozmer — APPROVED** [review]
Nice animation 😄

**Review by hermannakos — APPROVED** [review]
QA + 1
Love it!

**Pull request merged**
