### PR TITLE
[MBL-16704][Student] - Implement Dashboard Notification assert and routing in ShareExtensionE2ETest

### PR DESCRIPTION
**Pull request by kdeakinstructure**
Implement Dashboard Notification assert and routing in ShareExtension E2E t est.

E2E test run: https://app.bitrise.io/build/ad7699da-dc40-4c06-9cc9-00ec0c5a5157

refs: MBL-16704
affects: Student
release note: none

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by tamaskozmer — APPROVED** [review]

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Pull request merged**
