### PR TITLE
[MBL-17457][Teacher] Bulk publish updates

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test plan: In the ticket

refs: MBL-17457
affects: Teacher
release note: none

## Checklist

- [x] Tested in dark mode
- [x] Tested in light mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Review by hermannakos — APPROVED** [review]
QA + 1

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Pull request merged**
