### PR TITLE
[All] Fixed accessibility issues

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test plan: In the tickets

refs: MBL-16982, MBL-16975, MBL-16977, MBL-16984, MBL-16971, MBL-16978, MBL-16985
affects: All
release note: Fixed accessibility issues

## Checklist

- [x] Tested in dark mode
- [x] Tested in light mode
- [x] A11y checked

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kristofnemere — APPROVED** [review]
QA+1

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Pull request merged**
