### PR TITLE
Merge back offline feature

### PR DESCRIPTION
**Pull request by hermannakos**

### CODE REVIEW

**Comment by hermannakos** [comment]
[Student e2e](https://app.bitrise.io/build/fd17e03b-d193-42a7-8a29-7f3ec6c4e2c3)
[Student all-ui](https://app.bitrise.io/build/e510d8f3-9633-4743-a1d1-f0744382b812)
[Teacher e2e](https://app.bitrise.io/build/316d78e8-b108-4835-8049-6883d9e153e6)
[Teacher all-ui](https://app.bitrise.io/build/366c38cd-d900-4a1b-9a08-6d6510d3ef9d)

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Pull request merged**
