### PR TITLE
[Parent][MBL-13836] Add login help dialog button

### PR DESCRIPTION
**Pull request by Blackchai**

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1022843&projectid=20)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|0
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by Blackchai** [comment]
> So, if someone taps the question-mark, they will navigate to a dialog that will allow them to fire off an email requesting help? Might we want an intermediate step, where we pop up a page with a few pointers as to how to login correctly?

Reasonable, I'll ask Peyton about adding that. This ticket was just getting the old functionality there, as this is essentially what the current apps do.

**Comment by joehoag** [comment]
👍

**Pull request merged**
