### PR TITLE
[MBL-16753][Teacher] Submission comment disables annotations

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test plan: Description is in the ticket. The change that I removed was a legacy fix for some issues with the bottom sliding panel, smoke test the sliding panel thoroughly and look out for any potential issues. If there is any issue compare it with the current version.

refs: MBL-16753
affects: Teacher
release note: Fixed a bug where the annotation toolbar would disappear when entering a comment

## Checklist

- [x] Follow-up e2e test ticket created or not needed
- [x] Run E2E test suite or not needed
- [x] Tested in dark mode
- [x] Tested in light mode
- [x] A11y checked
- [x] Approve from product or not needed

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Review by hermannakos — APPROVED** [review]
QA + 1

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Review by kristofnemere — APPROVED** [review]
QA+1

**Pull request merged**
