### PR TITLE
[MBL-15859] [Student] [Teacher] -  Introduce new test related annotations

### PR DESCRIPTION
**Pull request by kdeakinstructure**
Introduce FlakyE2E and KnownBug annotations in both apps (Teacher, Student) to separate these breaking tests from nightly. (They'll also run but separately).

refs: MBL-15859
affects: Student, Teacher
release note: none

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by tamaskozmer — APPROVED** [review]

**Pull request merged**
