### PR TITLE
[MBL-17720][All] Updated Jetpack Compose

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test plan: Smoke test the Jetpack Compose screens (Calendar in all apps, most of the Parent app). There is also a linked accessibility ticket that this update fixes.

refs: MBL-17720
affects: All
release note: Accessibility improvements in the calendar

## Checklist

- [x] Tested in dark mode
- [x] Tested in light mode
- [x] A11y checked

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by hermannakos — APPROVED** [review]

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Pull request merged**
