### PR TITLE
[MBL-16228][Student] On Paper and No Submission assignments with a past due date display missing label

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test plan:
- In the ticket
- Also verify that the assignments will show up as missing if the teacher explicitly marks it in the gradebook (you need to create new assignments for this in your sandbox).

refs: MBL-16228
affects: Student
release note: Fixed a bug where on paper and no submission assignments would show as missing in grades.

--- edit or delete this section ---
## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [x] Follow-up e2e test ticket created or not needed
- [x] A11y checked
- [x] Approve from product or not needed

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Review by hermannakos — APPROVED** [review]

**Review by kristofnemere — APPROVED** [review]

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Pull request merged**
