### PR TITLE
Release Student 6.25.0 (252)

### PR DESCRIPTION
**Pull request by tamaskozmer**

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by tamaskozmer** [comment]
Broken test workflows successful rerun:

E2E: https://app.bitrise.io/build/2e3e4ae9-758e-461c-9f94-18d5a925ff05
UI-tablet: https://app.bitrise.io/build/df41ef54-e215-4f22-a597-65543259c843

**Review by kristofnemere — APPROVED** [review]

**Pull request merged**
