### PR TITLE
[MBL-17748][Parent] Feedback button

### PR DESCRIPTION
**Pull request by kristofnemere**
Test plan: 
- Go to assignment details screen.
- Tap on submission & rubric button.
- Check if the assignment's submission website loads and the selected user is correct.

refs: MBL-17748
affects: Parent
release note: Added submission feedback button to assignment details screen.

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td></td>
<td></td>
</tr>
<tr>
<td></td>
<td></td>
</tr>
</table>

## Checklist

- [x] Tested in dark mode
- [x] Tested in light mode
- [ ] A11y checked

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Review by tamaskozmer — APPROVED** [review]

**Review by hermannakos — APPROVED** [review]
QA + 1

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Pull request merged**
