### PR TITLE
Merge Calendar Feature

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test Plan:
- Student: Compare the functionality of the Calendar with the Play Store version of the app. See if anything is missing or behaves differently. Check the designs as well and compare the app with the designs.
- Teacher: Compare with the web.

## Checklist

- [x] Run e2e tests
- [x] A11y checked
- [x] Approve from product
- [x] Tested in light mode
- [x] Tested in dark mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by tamaskozmer** [comment]
Successful Teacher E2E test run: https://app.bitrise.io/build/f1016d2a-a6a6-4101-a2fb-ee6383044044
Student E2E test run (some tests failed, but those are known issues): https://app.bitrise.io/build/d5ad3a32-4ba1-4e7b-a727-c70abda498d1

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Pull request merged**
