### PR TITLE
[MBL-17361][Teacher] Fix Quiz details screen navigation

### PR DESCRIPTION
**Pull request by domonkosadam**
Test plan: See in the ticket

refs: MBL-17361
affects: Teacher
release note: Quiz details screen now opens is split view properly

## Checklist

- [x] Tested in dark mode
- [x] Tested in light mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Review by tamaskozmer — APPROVED** [review]
QA + 1

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Review by kristofnemere — APPROVED** [review]

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Pull request merged**
