### PR TITLE
[MBL-17471][Student][Teacher] Update Compose dependencies

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test plan: Smoke test Compose screens (Calendar on Teacher/Student, bulk publish progress in Teacher)

refs: MBL-17471
affects: Student, Teacher
release note: none

## Checklist

- [x] Tested in dark mode
- [x] Tested in light mode

### CODE REVIEW

**Review by hermannakos — APPROVED** [review]

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Pull request merged**
