### PR TITLE
[MBL-17009][Student] Convert scores to letter grades offline

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test plan: Verify that scores are correctly converted to letter grade in online and offline as well.

refs: MBL-17009
affects: Student
release note: none

## Checklist

- [x] Tested in dark mode
- [x] Tested in light mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kristofnemere — APPROVED** [review]

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Pull request merged**
