### PR TITLE
[MBL-16806][Student] -  Extend 'Retry' and 'Cancel' buttons' tap areas

### PR DESCRIPTION
**Pull request by kdeakinstructure**
Add some padding on 'Retry' and 'Cancel' buttons on the ShareExtension dialog.

refs: MBL-16806
affects: Student
release note: none

Test plan: Check tap areas manually.

## Checklist

- [x] Follow-up e2e test ticket created or not needed
- [x] Run E2E test suite or not needed
- [x] Tested in dark mode
- [x] Tested in light mode
- [x] A11y checked
- [x] Approve from product or not needed

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kristofnemere — APPROVED** [review]

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Pull request merged**
