### PR TITLE
[Student][Teacher][MBL-10782] Update inbox reply functionality

### PR DESCRIPTION
**Pull request by Blackchai**
While digging into this I noticed that monologues weren't working at all, so those have also been fixed. See the ticket for a detailed description regarding the reply behavior changes. The TL;DR is that we try to match web behavior as closely as possible.

### CODE REVIEW

**Comment by StephenBrough** [comment]
When replying to a single person in a group message, I'm seeing "<Name of sender>, +1". In other conversations, between two people, I see both names of the participants. Is that supposed to happen?

**Comment by StephenBrough** [comment]
Also kind of weird that reply and reply all in a conversation with two people has the same functionality.

**Comment by Blackchai** [comment]
> Also kind of weird that reply and reply all in a conversation with two people has the same functionality.

I agree, but that is how Canvas web works too :(.

**Comment by Blackchai** [comment]
> When replying to a single person in a group message, I'm seeing ", +1". In other conversations, between two people, I see both names of the participants. Is that supposed to happen?

I'm not sure, I didn't investigate that aspect of inbox as part of this. Do you think that's something that has changed or just a potential bug you've noticed?

**Comment by StephenBrough** [comment]
> I'm not sure, I didn't investigate that aspect of inbox as part of this. Do you think that's something that has changed or just a potential bug you've noticed?

Ah, I thought that was new behavior, but just tested it out on master and it's existing behavior.

**Pull request merged**
