### PR TITLE
[MBL-16669][All] Update Espresso lib dependency

### PR DESCRIPTION
**Pull request by domonkosadam**
refs: MBL-16669
affects: All
release note: none

## Checklist

- [ ] Tested in light mode
- [x] Run E2E Tests

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by kdeakinstructure** [comment]
E2E test are successfully ran to this PR. So no E2E test has broken because of this update.

**Review by kdeakinstructure — APPROVED** [review]

**Review by tamaskozmer — APPROVED** [review]

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Review by hermannakos — APPROVED** [review]

**Pull request merged**
