### PR TITLE
[MBL-16270][All] Improve mobile login

### PR DESCRIPTION
**Pull request by tamaskozmer**
refs: MBL-16270
affects: All
release note: Improved the login flow by saving the last institution's login page.

test plan:
- Acceptance criteria is in the ticket.
- Testing with a test sandbox will only remember and show the domain on the login screen. The reason for this is that we won't search for that school, but enter the domain directly.
- To see the name of the school you need to select a school from the search suggestions.

## Checklist

- [x] Follow-up e2e test ticket created or not needed
- [x] A11y checked
- [x] Approve from product or not needed

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kristofnemere — APPROVED** [review]

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Review by hermannakos — APPROVED** [review]

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Pull request merged**
