### PR TITLE
[MBL-16524][Teacher] - Create KDoc for complex functions and classes

### PR DESCRIPTION
**Pull request by kdeakinstructure**
KDoc Documentation for Teacher Page objects and the methods. 
Remove some unused methods + minor refactors.

refs: MBL-16524
affects: Teacher
release note: none

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kristofnemere — APPROVED** [review]

**Pull request merged**
