### PR TITLE
[MBL-16776][Student] Offline Page list

### PR DESCRIPTION
**Pull request by hermannakos**
Test plan: Test the Page list online and offline.

refs: MBL-16776
affects: Student
release note: none

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kristofnemere — APPROVED** [review]
QA+1

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Pull request merged**
