### PR TITLE
Release Teacher 1.35.0 (72)

### PR DESCRIPTION
**Pull request by andrasmaczak**

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Native Parent Install Page</p>

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Comment by andrasmaczak** [comment]
QA +1

**Pull request merged**
