### PR TITLE
[MBL-17780][Student] - Add 'Grading Period' string resource and display it on the Assignment List Page

### PR DESCRIPTION
**Pull request by kdeakinstructure**
Add 'Grading Period' string resource and display it on the Assignment List Page top-left corner.

refs: MBL-17780
affects: Student
release note: Displaying 'Grading Period' string on the Assignment List Page.

## Screenshots

<table>
<tr><th>Before</th><th>After</th></tr>
<tr>
<td>
image
</td>
<td>image</td>
</tr>
</table>

## Checklist

- [x] Tested in dark mode
- [x] Tested in light mode
- [ ] A11y checked
- [ ] Approve from product

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kristofnemere — APPROVED** [review]

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Pull request merged**
