### PR TITLE
Add score statistics to model, show on assignment

### PR DESCRIPTION
**Pull request by ndrewh**
iOS: complement to https://github.com/instructure/canvas-ios/pull/1421
API change: https://github.com/instructure/canvas-lms/pull/1669

### CODE REVIEW

**Comment by Blackchai** [comment]
Hi ndrewh! Thanks for your submission! Once it's no longer marked as a draft we'll be happy to code review it.

**Comment by Blackchai** [comment]
Just waiting on the associated canvas-lms changes to be merged so we can assist you in getting this passing builds for code review.

**Comment by ndrewh** [comment]
The API change got merged into canvas! I don't know the release schedule, but I imagine it'll get deployed soon, in which case this can be reviewed?

Thanks,
@ndrewh

**Comment by armstrongnate** [comment]
Moving to #973

**Pull request closed without merging**
