### PR TITLE
[MBL-16060][Student] - Remove calendar related skeleton classes

### PR DESCRIPTION
**Pull request by kdeakinstructure**
Delete calendar related "skeleton" classes. (Calendar is embedded-flutter in student and we cannot test it with Espresso)

refs: MBL-16060
affects: Student
release note: none

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by tamaskozmer — APPROVED** [review]

**Pull request merged**
