### PR TITLE
[Flutter-Parent] Fix strings that aren’t setup properly

### PR DESCRIPTION
**Pull request by CalvinKern**
Refer to the README.md to see what strings need for the extracting script.
Waiting to submit the generated arb file until we’re ready for another beta (or until we get a bitrise job setup to do this extracting).

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1022119&projectid=20)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|0
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by JordanMarshall** [comment]
> or until we get a bitrise job setup to do this extracting

This would be nice. It might also make sense to try generating the arb as part the PR workflow on bitrise, so we can catch these issues before they hit master.

**Comment by CalvinKern** [comment]
> This would be nice. It might also make sense to try generating the arb as part the PR workflow on bitrise, so we can catch these issues before they hit master.

Ooooh, I really like this idea. I'll try and get something up tomorrow. Not sure if we can detect when one fails though, by default they just get ignored and the script keeps going.

**Pull request merged**
