### PR TITLE
[MBL-17199][Student][Teacher] - Remove stubbed boolean flag from TestMetaData

### PR DESCRIPTION
**Pull request by kdeakinstructure**
Remove unused (and confusing) stubbed boolean flag from TestMetaData
Refactor usages in FileGenerator.

refs: MBL-17256
affects: Student, Teacher
release note: none

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by kdeakinstructure** [comment]
The only test which is failing has been fixed in the MBL-17256 ticket already. (Needed to change the Privacy Policy URL in our Apps).

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by tamaskozmer — APPROVED** [review]

**Pull request merged**
