### PR TITLE
[MBL-17002][Student][Teacher] Fix iWork MIME types

### PR DESCRIPTION
**Pull request by domonkosadam**
Test plan: Steps are in the ticket

refs: MBL-17002
affects: Student, Teacher
release note: none

## Checklist

- [x] Tested in light mode

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by tamaskozmer — APPROVED** [review]
QA + 1

**Pull request merged**
