### PR TITLE
[MBL-17822][Teacher] Filtering submissions by section doesn't open the correct students submission

### PR DESCRIPTION
**Pull request by hermannakos**
Test plan: See ticket.

refs: MBL-17822
affects: Teacher
release note: Fixed a bug, where not the correct student's submission was opened in SpeedGrader in some cases.

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Review by domonkosadam — APPROVED** [review]
QA + 1

**Pull request merged**
