### PR TITLE
Release Teacher 1.33.0 (70)

### PR DESCRIPTION
**Pull request by hermannakos**

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kdeakinstructure — DISMISSED** [review]
QA 👍

**Review by balintbartok — DISMISSED** [review]
QA + 1

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Review by domonkosadam — APPROVED** [review]
QA + 1

**Comment by tamaskozmer** [comment]
QA + 1

**Pull request merged**
