### PR TITLE
[MBL-16821][Student][Teacher] Pandata fixes

### PR DESCRIPTION
**Pull request by hermannakos**
Test plan: Check the events using charles, ping me for the faulty event list.

refs: MBL-16821
affects: Student, Teacher
release note: none

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kristofnemere — APPROVED** [review]

**Review by tamaskozmer — APPROVED** [review]

**Pull request merged**
