### PR TITLE
[Student][Teacher][MBL-13634] Add a11y label for discussion liking

### PR DESCRIPTION
**Pull request by CalvinKern**

### CODE REVIEW

**Comment by instructure-cx** [comment]
Scan submitted to Checkmarx

**Comment by instructure-cx** [comment]
### Checkmarx scan completed
[Full Scan Details](https://cxmgr.inssec.info/CxWebClient/ViewerMain.aspx?scanid=1014577&projectid=20)
#### Checkmarx Scan Summary
Severity|Count
---|---
High|0
Medium|0
Low|0
Informational|0

#### Violation Summary
Severity|Count
---|---

**Comment by JordanMarshall** [comment]
I'm testing a discussion (Student app, Pixel 2 XL, Android 10) and for some reason the descriptions for the like count and like button are not updated after the button is activated. I have to re-open the discussion details for them to update. This doesn't appear to be an issue in the current release APK.

**Comment by CalvinKern** [comment]
@JordanMarshall Ah, that's a good find, I think I can fix that.

**Pull request merged**
