### PR TITLE
[MBL-16630][Student] Sync Dashboard notification 

### PR DESCRIPTION
**Pull request by hermannakos**
Test plan: See ticket and design. Error handling is not finalized, test mostly the happy path.

refs: MBL-16630
affects: Student
release note: none

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by tamaskozmer — APPROVED** [review]

**Review by kristofnemere — APPROVED** [review]

**Review by kristofnemere — APPROVED** [review]
QA+1

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Pull request merged**
