### PR TITLE
[MBL-16783][Student] Only display synced tabs in Course Browser

### PR DESCRIPTION
**Pull request by kristofnemere**
Test plan: only synced course tabs should be enabled and clickable in course browser

refs: MBL-16783
affects: Student
release note: none

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by tamaskozmer — APPROVED** [review]

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Comment by kdeakinstructure** [comment]
'Collaborations' will remain visible. I would consider to make it disabled as well (since it's basically opens in a webview) if it's feasible.

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Pull request merged**
