### PR TITLE
Update translations

### PR DESCRIPTION
**Pull request by inst-danger**

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Review by balintbartok — APPROVED** [review]

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by droidwithme** [comment]
Build file 'E:\demos\test\canvas-android-master\canvas-android-master\apps\build.gradle' line: 19

A problem occurred evaluating root project 'apps'.
> Could not locate private data directory!

**Pull request merged**
