### PR TITLE
[MBL-17391][Student] Calendar swipe animation

### PR DESCRIPTION
**Pull request by hermannakos**
Test plan: Expand/collapse animation should trigger when swiping on the calendar. When the expand is disabled the swipe should have no effect either.

refs: MBL-17391
affects: Student
release note: none

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by tamaskozmer — APPROVED** [review]
QA + 1

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kristofnemere — APPROVED** [review]
QA+1

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Pull request merged**
