### PR TITLE
[MBL-16664][Teacher][Student] - Verify Instructure logo in AboutE2E test in Student + Implement AboutE2E test in Teacher

### PR DESCRIPTION
**Pull request by kdeakinstructure**
Assert instructure logo in student AboutE2E test.
Implement AboutE2E test in Teacher as well.
 
refs: MBL-16664
affects: Teacher, Student
release note: none

### CODE REVIEW

**Comment by kdeakinstructure** [comment]
This pull request depends on https://github.com/instructure/canvas-android/pull/1937

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by tamaskozmer — APPROVED** [review]

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Pull request merged**
