### PR TITLE
fix nightly tablet tests + implement delegate function for Matcher<View>

### PR DESCRIPTION
**Pull request by kdeakinstructure**
Fix nightly tablet tests.

Extend delegate functions to accept Matcher<View> type (OnViewWithMatcher)

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by tamaskozmer — APPROVED** [review]

**Pull request merged**
