### PR TITLE
[MBL-16255][Student] Share Extension findings

### PR DESCRIPTION
**Pull request by hermannakos**
refs: MBL-16255
affects: Student
release note: none

test plan:
- The dialog should have no dimming behind them
- The title of the Assignment FileUploadDialog should always be 'Submission'

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kristofnemere — APPROVED** [review]

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by tamaskozmer — APPROVED** [review]

**Pull request merged**
