### PR TITLE
[MBL-17655][All] Fix app restart

### PR DESCRIPTION
**Pull request by hermannakos**
Test plan: Easiest way to test is logging in with site admin and under Settings > Account Preferences changing the language.

refs: MBL-17655
affects: Student, Teacher, Parent
release note: Fixed a bug, where the app would not restart after changing the language.

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Parent Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kristofnemere — APPROVED** [review]
QA+1

**Review by tamaskozmer — APPROVED** [review]

**Review by kdeakinstructure — APPROVED** [review]
QA 👍

**Pull request merged**
