### PR TITLE
[MBL-16485][Student] -  Add new assignment details interaction tests

### PR DESCRIPTION
**Pull request by kdeakinstructure**
Add some new cases to AssignmentDetailsInteractionTest
Refactor method names in AssignmentDetailsPage
Filter to not submitted course in goToAssignmentFromList method
Add additional new cases
Add some assertions to existing cases
Refactor

refs: MBL-16485
affects: Student
release note: none

NOTE: This pull request is depending on MBL-16380 issue's pull-request made by @kristofnemere . Those changes are displayed here as well because it's not in the master yet. When he merges it, i will refresh this pull-request and only the relevant changes will be seen.

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by kristofnemere — APPROVED** [review]

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by hermannakos — APPROVED** [review]

**Pull request merged**
