### PR TITLE
[MBL-16495][Student][Teacher] Disable gif keyboard

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test plan: 
- Bug steps are in the ticket
- Smoke text edit text and RCEditor behavior in both appps.

refs: MBL-16495
affects: Student, Teacher
release note: none

## Checklist

- [x] Follow-up e2e test ticket created or not needed
- [x] Run E2E test suite or not needed
- [x] Tested in dark mode
- [x] Tested in light mode
- [x] A11y checked
- [x] Approve from product or not needed

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by kristofnemere** [comment]
Not working with Switfkey.

**Review by hermannakos — APPROVED** [review]

**Review by kristofnemere — APPROVED** [review]

**Review by kdeakinstructure — APPROVED** [review]
QA 👍  (We have seen and discussed this on the weekly android team meeting)

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Pull request merged**
