### PR TITLE
[MBL-16083][Student][Teacher] Dark mode refinements

### PR DESCRIPTION
**Pull request by tamaskozmer**
Test plan: 
- Verify all the bugs are fixed that are listed in the ticket.
- Smoke test the app in dark mode, because many colors where changed (don't need to be as detailed as in the complete dark mode story)

Review notes:
- Might be a good idea to go commit by commit, each commit represents one issue from the ticket apart from the last 2 navigation issues that are related.

refs: MBL-16083
affects: Student, Teacher
release note: none

### CODE REVIEW

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Review by hermannakos — APPROVED** [review]

**Review by kdeakinstructure — APPROVED** [review]
QA 👍  (You already know about the one inconsistent bug which I have found via smoke testing, but we agreed that it probably won't be fixed in this pr, and we should see if we can fix it at all, because of it's inconsistency)

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Comment by inst-danger** [comment]
<p>Teacher Install Page</p>

**Comment by inst-danger** [comment]
<p>Student Install Page</p>

**Pull request merged**
